name: Build - tar.gz
description: 'Build .tar.gz release'

inputs:
  runtime:
    description: '.NET runtime'
    required: true
  
runs:
  using: "composite"
  steps:

  - name: Build release
    run: dotnet publish cli --configuration Release --self-contained --runtime ${{ inputs.runtime }} --output publish/cli/${{ inputs.runtime }}
    shell: bash

  - name: Package tar.gz
    run: |
      pushd publish/cli/${{ inputs.runtime }}/

      tar -czf "tangram-bamboo_${{ env.VERSION }}_${{ inputs.runtime }}.tar.gz" *
      sha256sum tangram-bamboo_${{ env.VERSION }}_${{ inputs.runtime }}.tar.gz > tangram-bamboo_${{ env.VERSION }}_${{ inputs.runtime }}.tar.gz.sha256
        
      mv tangram-bamboo_${{ env.VERSION }}_${{ inputs.runtime }}.tar.gz        ${{ github.workspace }}
      mv tangram-bamboo_${{ env.VERSION }}_${{ inputs.runtime }}.tar.gz.sha256 ${{ github.workspace }}

      popd
    shell: bash
